Basic auth
programandonocosmos/cashtools-app pull request #1
Opened 2022-10-10 02:06 UTC by davisuga

- lib update
- added needed providers
- feat:  basic user types
- feat: basic auth reducer
- feat: basic auth context
- feat: basic visual offline login
- feat: basic relay config
- feat: added createUser mutation
- feat: added generated queries
- feat(login): added query
- feat: added sign up mutation

2022-10-23 19:40 UTC, cl3t0 requested changes

2022-10-23 19:40 UTC, cl3t0 commented on src/RelayEnv.res
> +    "http://192.168.1.187:8080/graphql",
You should not hard code an IP.

2022-10-23 19:40 UTC, cl3t0 commented on src/PersistReducer.res
> +  let result = reducer(state, action)
You can change the variable name to something more meaningful like `newState`.

2022-10-23 19:40 UTC, cl3t0 commented on src/navigation/Navigation.res
> +    let (state, _dispatch) = Context.AuthContext.use()
You should use UseAuth instead of AuthContext here.

2022-10-23 19:40 UTC, cl3t0 commented on src/navigation/Navigation.res
> +          <Screen name="InsertCode" component=InsertCode.make />
Missing SignUp screen here, no?

2022-10-27 22:30 UTC, davisuga commented on src/RelayEnv.res
> +    "http://192.168.1.187:8080/graphql",
Fixed

2022-10-27 22:30 UTC, davisuga commented on src/PersistReducer.res
> +  let result = reducer(state, action)
Fixed

2022-10-27 22:30 UTC, davisuga commented on src/navigation/Navigation.res
> +    let (state, _dispatch) = Context.AuthContext.use()
Fixed

2022-10-30 21:21 UTC, cl3t0 approved these changes

2022-10-30 21:24 UTC, merged